version: "3.0"
services:
  public-service:
      build: ./public-service
      ports:
        - 8080:8080
      depends_on:
          - subscription-service
          - email-service
      environment:
        SUBSCRIPTION_SERVICE_HOSTNAME: subscription-service
        SUBSCRIPTION_SERVICE_PORT: 8081
        PORT: 8080
  subscription-service:
      build: ./subscription-service
      ports:
        - 8081:8081
      depends_on:
          - email-service
      environment:
        EMAIL_SERVICE_HOSTNAME: email-service
        EMAIL_SERVICE_PORT: 8082
        PORT: 8081
  email-service:
      build: ./email-service
      ports:
        - 8082:8082
      environment:
        PORT: 8082
