openapi: 3.0.0
info:
  title: Email Service
  description: Private email API for email notifications
  version: 1.0.0
schemes:
  - http
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
paths:
  /emails:
    post:
      tags:
        - Emails
      summary: Send a new email.
      description: Sends a new email notification.
      requestBody:
        description: Email.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/definitions/email'
      produces:
        - application/json
      responses:
        201:
          description: Email sent.
        400:
          $ref: '#/responses/BadRequest'
        500:
          $ref: '#/responses/ServerError'
responses:
  BadRequest:
    description: Bad Request
    content:
      application-json:
        schema:
          $ref: '#/definitions/error'
  Unauthorized:
    description: Unauthorized
  ServerError:
    description: Server error
definitions:
  error:
    type: object
    properties:
      error:
        type: string
        example: "Error description"
      timestamp:
        type: string
        example: "7/2/2021 11:21:48"
    required:
      - error
  subscription:
    type: object
    properties:
      email:
        type: string
        example: example@example.com
      newsletterId:
        type: string
        example: HKnhQiVMVgMal93d
      firstName:
        type: string
        required: false
        example: Name
      gender:
        type: string
        required: false
        example: F
      dateOfBirth:
        type: date
        example: "1997-12-16"
      consentFlag:
        type: boolean
        example: true
  email:
    type: object
    properties:
      subscription:
        $ref: '#/definitions/subscription'
      emailBody:
        type: string
        example: Body of the email.

